# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               MK
tagline:             'Dat theme tho'
description:         'Some good stuff here'
url:                 http://mjklin.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Klingman
  url:               https://twitter.com/mjkling
  email:             mjklin@gmail.com

# Custom vars
version:             1.0.0
